site_dir: docs/2020.x
site_url: https://aimeos.org/docs/2020.x/


site_name: Documentation
repo_url: https://github.com/aimeos/aimeos-docs
edit_uri: blob/master/content/
markdown_extensions:
  - toc:
      baselevel: 2
      permalink: '#'
  - def_list
  - admonition
  - pymdownx.tabbed
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.superfences
plugins:
  - search
docs_dir: content
theme:
  name: material
  custom_dir: theme
  favicon: _assets/favicon.svg
  logo: https://aimeos.org/fileadmin/logos/logo-aimeos-blue.svgz
  font:
    text: Noto Sans
extra_css:
  - _assets/aimeos.css
extra_javascript:
  - /docs/versions.js
extra:
  disqus: aimeos
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aimeos
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/Aimeos
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/aimeos
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/c/aimeos
tracking:
  url: https://aimeos.org/stats
  siteid: 1


nav:
  - Getting started:
    - Laravel:
      - Overview: start/laravel/index.md
    - Symfony:
      - Overview: start/symfony/index.md
    - TYPO3:
      - Overview: start/typo3/index.md
    - Development:
      - Architecture: start/developer/architecture.md
      - Dependency container: start/developer/context.md
      - Git workflow: start/developer/git-workflow.md
      - Phing build system: start/developer/phing.md
      - Create extensions: start/developer/extensions.md
      - Add translations:  start/developer/translations.md
  - User manual:
    - Filtering lists:  manual/filtering-lists.md
    - Shop setup:
      - Working with sites:  manual/working-with-sites.md
      - Currencies/languages: manual/locales.md
      - Payment/Delivery:
        - Available services: manual/services.md
        - Service details: manual/service-details.md
        - Adding features: manual/service-decorators.md
      - Basket plugins:
        - Available plugins: manual/plugins.md
        - Plugins details: manual/plugin-details.md
    - Manage content:
      - Products:
        - Available products: manual/products.md
        - Product details: manual/product-details.md
      - Catalog:
        - Manage categories: manual/categories.md
        - Category details: manual/category-details.md
      - Vouchers/Coupons:
        - Available coupon: manual/coupons.md
        - Coupon details: manual/coupon-details.md
        - Adding features: manual/coupon-decorators.md
      - Orders: manual/orders.md
      - Subscriptions: manual/subscriptions.md
  - Frontend:
    - HTML:
      - Overview: frontend/html/index.md
      - Themes: frontend/html/themes.md
    - JSON API:
      - Getting started: frontend/jsonapi/index.md
      - Search basics: frontend/jsonapi/basics.md
      - Catalog handling: frontend/jsonapi/catalog.md
      - Manage baskets: frontend/jsonapi/baskets.md
      - Basket products: frontend/jsonapi/basket-products.md
      - Basket addresses: frontend/jsonapi/basket-addresses.md
      - Basket services: frontend/jsonapi/basket-services.md
      - Basket coupons: frontend/jsonapi/basket-coupons.md
      - Manage orders: frontend/jsonapi/orders.md
    - Controller:
      - Product: frontend/controller/product.md
  - Admin backend:
    - HTML:
      - Overview: backend/html/index.md
    - JSON API:
      - Filter: backend/jsonapi/filter.md
  - Cronjobs: cronjobs.md
  - Data storage:
    - Working with managers: storage/working-with-manaagers.md
  - Infrastructure:
    - Caching: infrastructure/caching.md
    - Logging: infrastructure/logging.md
  - Changelog:
    - 2019.x -> 2020.x : changelog/2020.x.md
    - 2018.x -> 2019.x : changelog/2019.x.md
    - 2017.x -> 2018.x : changelog/2018.x.md
